force-app/main/default/objects/Email_to_Flow_Received__e/Email_to_Flow_Received__e.object-meta.xml
<CustomObject>
    <description>Platform Event that will be published from the EmailToFlow class once an email is received</description>
    <label>Email to Flow Received</label>
    <pluralLabel>Emails to Flow Received</pluralLabel>
</CustomObject>

force-app/main/default/objects/Email_to_Flow_Received__e/fields/Content_Version_Ids__c.field-meta.xml
<CustomField>
    <fullName>Content_Version_Ids__c</fullName>
    <description>Id&apos;s of Content Version for Email Attachments</description>
    <label>Content Version Ids</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Email_to_Flow_Received__e/fields/Email_CC_Addresses__c.field-meta.xml
<CustomField>
    <fullName>Email_CC_Addresses__c</fullName>
    <description>A list of CC Addresses separated by a comma</description>
    <label>Email CC Addresses</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Email_to_Flow_Received__e/fields/Email_From_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_From_Address__c</fullName>
    <label>Email From Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Email_to_Flow_Received__e/fields/Email_From_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_From_Name__c</fullName>
    <label>Email From Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Email_to_Flow_Received__e/fields/Email_HTML_Body__c.field-meta.xml
<CustomField>
    <fullName>Email_HTML_Body__c</fullName>
    <label>Email HTML Body</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Email_to_Flow_Received__e/fields/Email_In_ReplyTo__c.field-meta.xml
<CustomField>
    <fullName>Email_In_ReplyTo__c</fullName>
    <label>Email In ReplyTo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Email_to_Flow_Received__e/fields/Email_Is_HTML_Truncated__c.field-meta.xml
<CustomField>
    <fullName>Email_Is_HTML_Truncated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Email Is HTML Truncated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Email_to_Flow_Received__e/fields/Email_Is_Text_Body_Truncated__c.field-meta.xml
<CustomField>
    <fullName>Email_Is_Text_Body_Truncated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Email Is Text Body Truncated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Email_to_Flow_Received__e/fields/Email_Message_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Message_Id__c</fullName>
    <label>Email Message Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Email_to_Flow_Received__e/fields/Email_References__c.field-meta.xml
<CustomField>
    <fullName>Email_References__c</fullName>
    <description>List of Email References separated by a comma</description>
    <label>Email References</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Email_to_Flow_Received__e/fields/Email_Reply_To__c.field-meta.xml
<CustomField>
    <fullName>Email_Reply_To__c</fullName>
    <label>Email Reply To</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Email_to_Flow_Received__e/fields/Email_Subject__c.field-meta.xml
<CustomField>
    <fullName>Email_Subject__c</fullName>
    <label>Email Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Email_to_Flow_Received__e/fields/Email_Text_Body__c.field-meta.xml
<CustomField>
    <fullName>Email_Text_Body__c</fullName>
    <label>Email Text Body</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Email_to_Flow_Received__e/fields/Email_To_Addresses__c.field-meta.xml
<CustomField>
    <fullName>Email_To_Addresses__c</fullName>
    <label>Email To Addresses</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Email_to_Flow_Received__e/fields/Envelope_From_Address__c.field-meta.xml
<CustomField>
    <fullName>Envelope_From_Address__c</fullName>
    <label>Envelope From Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Email_to_Flow_Received__e/fields/Envelope_To_Address__c.field-meta.xml
<CustomField>
    <fullName>Envelope_To_Address__c</fullName>
    <label>Envelope To Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EmailToFlow.cls
/* @author:         Praxis Solutions, LLC
 * @authorEmail:    support@getpraxis.com
 * @Description:    Email Service Publishes Platform Event that can be subscribed to by Flows or Apex.
 */

global class EmailToFlow implements Messaging.inboundEmailHandler{
 
    global Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email, Messaging.InboundEnvelope env) {
        Messaging.InboundEmailResult result = new Messaging.InboundEmailResult();
        
        Email_to_Flow_Received__e emailPE = new Email_to_Flow_Received__e (
            Email_From_Address__c           = email.FromAddress,
            Email_From_Name__c              = email.FromName,
            Email_Subject__c                = email.Subject,
            Email_HTML_Body__c              = email.HTMLBody,
            Email_Text_Body__c              = email.PlainTextBody,
            Email_Message_Id__c             = email.MessageId,
            Email_In_ReplyTo__c             = email.InReplyTo,
            Email_Is_HTML_Truncated__c      = email.HTMLBodyIsTruncated,
            Email_Is_Text_Body_Truncated__c = email.PlainTextBodyIsTruncated,
            Email_Reply_To__c               = email.ReplyTo,
            Envelope_From_Address__c        = env.FromAddress,
            Envelope_To_Address__c          = env.ToAddress,
            Email_To_Addresses__c           = email.ccAddresses != null ? String.join(email.toAddresses, ',') : null,
            Email_CC_Addresses__c           = email.ccAddresses != null ? String.join(email.ccAddresses, ','): null,
            Email_References__c             = email.References  != null ? String.join(email.References, ',') : null,
            Content_Version_Ids__c          = ConvertAttachmentsToCV(email)
        );
       
        //Publish Platform Event
        EventBus.publish(emailPE);
        return result;
    }
    
    //Convert All Attachments to List of ContentVersion
    private static String ConvertAttachmentsToCV(Messaging.InboundEmail email){
        List<ContentVersion>CVRecords = new List<ContentVersion>();
        //Convert binary attachments to ContentVersion
        if (email.BinaryAttachments != null && !email.BinaryAttachments.isEmpty()){
            for (Messaging.InboundEmail.BinaryAttachment BinAttach : email.BinaryAttachments){
                ContentVersion CVRecord = new ContentVersion();
                CVRecord.Title = BinAttach.FileName;
                CVRecord.VersionData = BinAttach.Body;
                CVRecord.PathOnClient = '/' + BinAttach.FileName ;
                CVRecords.add(CVRecord);
            }
        }
        //Convert text attachments to PDF ContentVersion
        if (email.TextAttachments != null && !email.TextAttachments.isEmpty()){
            for (Messaging.InboundEmail.TextAttachment TextAttach : email.TextAttachments){
                ContentVersion CVRecord = new ContentVersion();
                CVRecord.Title = TextAttach.FileName;
                CVRecord.VersionData = Blob.ToPDF(TextAttach.Body);
                CVRecord.PathOnClient = '/' + TextAttach.FileName.Replace('.','') + '.pdf' ;
                CVRecords.add(CVRecord);
            }
        }

        String cvRecordIDs = '';
        //return only if Attachments exist
        if(CVRecords != null && !CVRecords.isEmpty()){
            insert CVRecords;
            List<String> Ids = new List<String>();
            for(ContentVersion CV : CVRecords){
                Ids.add(CV.Id);
            }
            cvRecordIDs = string.join(Ids,',');
        }

        return cvRecordIDs;
    }
}